#可选项，需要定义区分不同类别代码时才需要配置source
source:

  # 提供产品代码库中直接以源码形式存在的第三方代码目录或代码文件名的正则表达。
  # 此处备注的第三方代码在后续统计代码量环节会被排除，若代码库中不存在需要排除的第三方代码，该项配置标识可为空
  third_party_source:
    #第三方代码文件的正则表达式，若无统一标识格式，可以指定具体目录，样例可参考test_source举例
    filepath_regex: ["config/.*", "resources/.*","docs/.*","ci/.*", "scripts/.*", "public/.*", ".*eslint.*", ".*config.*", "__tests__", "__test__","__test__/.*","test/.*", "__mocks__", "__mocks__/.*", "server/src/public/static/js/.*"]